[package]
name = "virtdisk-fuzz"
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
publish = false

[workspace]

[dependencies]
honggfuzz = "=0.5.62"
virtdisk = { path = ".." }
tempfile = "3.23"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
debug = 1
overflow-checks = true
